#!/bin/sh

set -e -u

cd cdk8s
REVISION=$(cat .git/refs/heads/main)                # $(git branch --show-current)/$(git rev-parse HEAD)
TAG=$(cat .git/refs/heads/main | head -c 7)
SOURCE="https://github.com/TilBlechschmidt/cluster" # $(git config --get remote.origin.url)
cd ..

echo "Tag: $TAG"
echo "Src: $SOURCE"
echo "Rev: $REVISION"
echo ""

flux push artifact oci://flux.blechschmidt.dev/ci:$TAG \
  --path="cluster" \
  --source="$SOURCE" \
  --revision="$REVISION" \
  --creds flux:$REGISTRY_TOKEN

echo ""

flux tag artifact oci://flux.blechschmidt.dev/ci:$TAG \
  --tag latest \
  --creds flux:$REGISTRY_TOKEN
