# This requires the pull secret to be placed in the same namespace
# flux create secret oci registry-password --url=flux.blechschmidt.dev --username=flux --password='...'
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-registry-ci
  namespace: flux-system
spec:
  interval: 1m
  url: oci://flux.blechschmidt.dev/ci
  ref:
    tag: latest
  provider: generic
  secretRef:
    name: registry-password
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  sourceRef:
    kind: OCIRepository
    name: flux-registry-ci
  interval: 1m
  retryInterval: 2m
  path: ./
  prune: true
  wait: true
  timeout: 2m
